export enum AuditStatus {
  PASSED = 'PASSED',
  FAILED = 'FAILED',
  REJECTED_REQUEST = 'REJECTED_REQUEST',
  UNDER_REVIEW = 'UNDER_REVIEW',
  EXPIRED = 'EXPIRED',
}

export enum AuditWorkflowStage {
  APPLICATION_INTAKE = 'APPLICATION_INTAKE',
  EVIDENCE_REVIEW = 'EVIDENCE_REVIEW',
  FIELD_ASSESSMENT = 'FIELD_ASSESSMENT',
  PANEL_DECISION = 'PANEL_DECISION',
  PUBLICATION_VERIFICATION = 'PUBLICATION_VERIFICATION',
  ANNUAL_RENEWAL = 'ANNUAL_RENEWAL',
}

export enum CertificationStatus {
  VALID = 'VALID',
  EXPIRED = 'EXPIRED',
  INVALID = 'INVALID',
  NOT_CERTIFIED = 'NOT_CERTIFIED',
}

export enum RiskLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum SubmissionStatus {
  NEW = 'NEW',
  REVIEWING = 'REVIEWING',
  CONTACTED = 'CONTACTED',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
  REVIEWED = 'REVIEWED',
}

export type AdminPermissionCode = string;
